Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UpLoadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpq
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: cmj19971227
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConnes: 10
  MaxOpenConnes: 30
JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200